apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olivetti
  template:
    metadata:
      labels:
        app: olivetti
    spec:
      containers:
        - name: olivetti-container
          image: amishkar/olivetti-app:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: olivetti-service
spec:
  type: LoadBalancer
  selector:
    app: olivetti
  ports:
    - port: 80
      targetPort: 5000